/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'alert-rules': { count: 4, loc: 574 },
  'alerts': { count: 4, loc: 453 },
  'api-tests': { count: 12, loc: 879 },
  'audit-logs': { count: 4, loc: 319 },
  'database': { count: 5, loc: 132 },
  'devices': { count: 4, loc: 543 },
  'http-foundation': { count: 8, loc: 252 },
  'identity': { count: 8, loc: 597 },
  'middleware': { count: 3, loc: 168 },
  'models': { count: 15, loc: 428 },
  'plants': { count: 4, loc: 349 },
  'process-units': { count: 4, loc: 849 },
  'routes': { count: 1, loc: 245 },
  'runtime': { count: 2, loc: 59 },
  'scenarios': { count: 4, loc: 430 },
  'simulation-engine': { count: 3, loc: 355 },
  'simulations': { count: 4, loc: 640 },
  'tag-readings': { count: 4, loc: 394 },
  'tags': { count: 4, loc: 814 },
  'tooling': { count: 5, loc: 225 },
  'websockets': { count: 4, loc: 630 },
}

export const UNCLAIMED: string[] = []
