### Get All Plants
GET http://localhost:8080/api/v1/plants

### Create Plant
POST http://localhost:8080/api/v1/plants
Content-Type: application/json

{
	"name":"Anaerobic Digestion Plant",
	"location":"Hsinchu City, Taiwan",
	"description":"Pilot Plant",
	"status":"ACTIVE"
}

### Get Plant By ID
@plantId = 6203ddf0-52a1-4251-bafa-193f694d7601
GET http://localhost:8080/api/v1/plants/{{plantId}}

### Update Plant By ID
PUT http://localhost:8080/api/v1/plants/{{plantId}}
Content-Type: application/json

{
	"name":"Updated Plant",
	"status":"INACTIVE"
}

### Delete Plant By ID
DELETE http://localhost:8080/api/v1/plants/{{plantId}}
Content-Type: application/json

{
	"action":"delete"
}

