### Get All Plants
GET http://localhost:8080/api/v1/plants

### Create Plant
POST http://localhost:8080/api/v1/plants
Content-Type: application/json

{
	"name":"Anaerobic Digestion Plant",
	"location":"Hsinchu City, Taiwan",
	"description":"Pilot Plant",
	"status":"ACTIVE"
}

### Get Plant By ID
@plantId = 264dbd8e-ce3e-4652-bddf-1a739e5b6c7f
GET http://localhost:8080/api/v1/plants/{{plantId}}

