### Create Process Unit for Anaerobic Digestion Plant
@plantId = 6203ddf0-52a1-4251-bafa-193f694d7601
POST http://localhost:8080/api/v1/plants/{{plantId}}/process-units
Content-Type: application/json

{
	"name": "Methane Tank",
	"type": "Anaerobic Digestion",
	"description": "For methanogenesis process",
	"status": "ACTIVE"
}

### Get Process Units for Anaerobic Digestion Plant
GET http://localhost:8080/api/v1/plants/{{plantId}}/process-units

### Get Process Unit Details
@processUnitId = aaafa5d1-673e-46b6-ada8-93e5929cc55f
GET http://localhost:8080/api/v1/process-units/{{processUnitId}}

### Update Process Unit
PUT http://localhost:8080/api/v1/process-units/{{processUnitId}}
Content-Type: application/json

{
	"name": "Methane Reactor",
	"type": "Anaerobic Digestion",
	"description": "Updated methanogenesis process unit for methane production stabilization and biogas quality monitoring.",
	"status": "MAINTENANCE",
	"position": {
			"x":120.45,
			"y":-10.25
	}
}

### Delete Process Unit
DELETE http://localhost:8080/api/v1/process-units/{{processUnitId}}
Content-Type: application/json

{
	"action": "delete"
}
