### Create Process Unit for Anaerobic Digestion Plant
@plantId = 86ca5d65-3c1e-4dbd-9c5a-46ea68a897be
POST http://localhost:8080/api/v1/plants/{{plantId}}/process-units
Content-Type: application/json

{
	"name": "Methane Tank",
	"type": "Anaerobic Digestion",
	"description": "For methanogenesis process",
	"status": "ACTIVE"
}

### Get Process Units for Anaerobic Digestion Plant
GET http://localhost:8080/api/v1/plants/{{plantId}}/process-units
