/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlcRouteImport } from './routes/_authenticated/plc'
import { Route as AuthenticatedPlantSetupRouteImport } from './routes/_authenticated/plant-setup'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlarmsRouteImport } from './routes/_authenticated/alarms'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlcRoute = AuthenticatedPlcRouteImport.update({
  id: '/plc',
  path: '/plc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlantSetupRoute = AuthenticatedPlantSetupRouteImport.update({
  id: '/plant-setup',
  path: '/plant-setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlarmsRoute = AuthenticatedAlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AuthenticatedAlarmsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/plant-setup': typeof AuthenticatedPlantSetupRoute
  '/plc': typeof AuthenticatedPlcRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AuthenticatedAlarmsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/plant-setup': typeof AuthenticatedPlantSetupRoute
  '/plc': typeof AuthenticatedPlcRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/alarms': typeof AuthenticatedAlarmsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/plant-setup': typeof AuthenticatedPlantSetupRoute
  '/_authenticated/plc': typeof AuthenticatedPlcRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/dashboard'
    | '/equipment'
    | '/plant-setup'
    | '/plc'
    | '/settings'
    | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/dashboard'
    | '/equipment'
    | '/plant-setup'
    | '/plc'
    | '/settings'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/alarms'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipment'
    | '/_authenticated/plant-setup'
    | '/_authenticated/plc'
    | '/_authenticated/settings'
    | '/_authenticated/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plc': {
      id: '/_authenticated/plc'
      path: '/plc'
      fullPath: '/plc'
      preLoaderRoute: typeof AuthenticatedPlcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plant-setup': {
      id: '/_authenticated/plant-setup'
      path: '/plant-setup'
      fullPath: '/plant-setup'
      preLoaderRoute: typeof AuthenticatedPlantSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alarms': {
      id: '/_authenticated/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AuthenticatedAlarmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlarmsRoute: typeof AuthenticatedAlarmsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedPlantSetupRoute: typeof AuthenticatedPlantSetupRoute
  AuthenticatedPlcRoute: typeof AuthenticatedPlcRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlarmsRoute: AuthenticatedAlarmsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedPlantSetupRoute: AuthenticatedPlantSetupRoute,
  AuthenticatedPlcRoute: AuthenticatedPlcRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
